version: "3"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - tranner-network

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - tranner-network

  account-service:
    build:
      context: ./account-service
    ports:
      - "8081:8081"
    networks:
      - tranner-network

  external-api-proxy:
    build:
      context: ./external-api-proxy
    ports:
      - "8085:8085"
    networks:
      - tranner-network

networks:
  tranner-network:
    driver: bridge
