version: "3"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tranner-network

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - tranner-network

  account-service:
    build:
      context: ./account-service
    ports:
      - "8081:8081"
    networks:
      - tranner-network

  external-api-proxy:
    build:
      context: ./external-api-proxy
    ports:
      - "8085:8085"
    networks:
      - tranner-network

networks:
  tranner-network:
    driver: bridge
volumes:
  mysql-data: