version: "3"
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - account-service
    networks:
      - tranner-network

  account-service:
    build:
      context: ./account-service
    ports:
      - "8081:8081"
    networks:
      - tranner-network

networks:
  tranner-network:
    driver: bridge
