server:
  port: 8080
  forward-headers-strategy: framework

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${HOST:3.35.102.134}:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
        - id: login-success
          uri: lb://account-service
          predicates:
              - Path=/login/success
        - id: account-service-oauth2
          uri: lb://account-service
          predicates:
            - Path=/oauth2/authorization/**
        - id: account-service-login
          uri: lb://account-service
          predicates:
            - Path=/login/**
        - id: travel-plan-service
          uri: lb://travel-plan-service
          predicates:
            - Path=/api/plan/**
        - id: travel-plan-search-service
          uri: lb://external-api-proxy
          predicates:
            - Path=/api/search/**
        - id: travel-discovery-service
          uri: lb://external-api-proxy
          predicates:
            - Path=/api/discovery/**
      codecs:
        default-charset: UTF-8
        charset:
          accept: UTF-8

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.security: DEBUG