server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${HOST}:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
        - id: travel-plan-service
          uri: lb://travel-plan-service
          predicates:
            - Path=/api/plan/**
        - id: travel-plan-search-service
          uri: lb://travel-plan-search-service
          predicates:
            - Path=/api/search/**
        - id: travel-discovery-service
          uri: lb://travel-discovery-service
          predicates:
            - Path=/api/discovery/**

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.security: DEBUG