server:
  port: 8085

spring:
  data:
    mongodb:
      uri: {MONGO_DB_URI}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

logging:
  level:
    root: WARN
    com.tranner.account_service: ERROR
