server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb://${HOST}:27017/external-api-db

  redis:
    host: ${REDIS_HOST}
    port: 6379


logging:
  level:
    root: INFO
    com.tranner.account_service: DEBUG
