eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: external-api-proxy

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 기본값은 dev

google:
  maps:
    api:
      key: ${GOOGLE_PLACES_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET_NAME}
