server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/external-api-db

  redis:
    host: localhost
    port: 6379


logging:
  level:
    root: INFO
    com.tranner.account_service: DEBUG
