server:
  port: 8085

spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379

logging:
  level:
    root: WARN
    com.tranner.account_service: ERROR
