server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_db
    username: root
    password: root

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.tranner.account_service: DEBUG
