server:
  port: 8761

spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: false  # (유레카 클라이언트 기반) 다른 서비스들의 정보를 fetch 유무
    service-url:
      defaultZone: http://${HOST:3.35.102.134}:8761/eureka # 설정을 하지 않으면 기본 http://localhost:8761/ 로 연동된다.

management:
  endpoints:
    web:
      exposure:
        include: "*"