name: Verify Changed Services

on:
  pull_request:
    branches: [ "main" ]

jobs:
  verify-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [account-service, api-gateway, eureka-server, external-api-proxy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if service has changed
        id: changes
        run: |
          if git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep "${{ matrix.service }}/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Set up JDK
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests for ${{ matrix.service }}
        if: steps.changes.outputs.changed == 'true'
        run: ./gradlew :${{ matrix.service }}:bootJar
