name: Verify Changed Services

on:
  pull_request:
    branches: [ "main" ]

jobs:
  verify-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [account-service, api-gateway, eureka-server, external-api-proxy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check changes
        id: changes
        run: |
          echo "CHANGED=false" >> $GITHUB_ENV
          if git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep "${{ matrix.service }}/"; then
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Set up JDK
        if: env.CHANGED == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Export secrets for ${{ matrix.service }}
        if: env.CHANGED == 'true'
        run: |
          echo "HOST=${{ secrets.HOST }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "PROD_DB_URL=${{ secrets.PROD_DB_URL }}" >> $GITHUB_ENV
          echo "PROD_DB_USERNAME=${{ secrets.PROD_DB_USERNAME }}" >> $GITHUB_ENV
          echo "PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_PLACES_KEY=${{ secrets.GOOGLE_PLACES_KEY }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> $GITHUB_ENV

      - name: Build JAR for ${{ matrix.service }}
        if: env.CHANGED == 'true'
        run: ./gradlew :${{ matrix.service }}:test
