name: Build and Push All Modules to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [account-service, api-gateway, eureka-server, external-api-proxy]  # 너 프로젝트의 모듈 이름들

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build JAR for ${{ matrix.service }}
        run: ./gradlew :${{ matrix.service }}:bootJar -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ matrix.service }}-${{ env.IMAGE_TAG }} ./${{ matrix.service }}

      - name: Push to ECR
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:${{ matrix.service }}-${{ env.IMAGE_TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ matrix.service }}-${{ env.IMAGE_TAG }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ matrix.service }}-${{ env.IMAGE_TAG }}

      - name: Download base task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ matrix.service }}-task \
            --query 'taskDefinition' \
            > task-definition.json

      - name: Replace image URL
        run: |
          jq '.containerDefinitions[0].image = "${{ secrets.ECR_URI }}:${{ matrix.service }}-${{ github.sha }}"' \
          task-definition.json > new-task-def.json

      - name: Register new task definition
        id: register-task-def
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json > output.json
          echo "TASK_DEF_ARN=$(jq -r '.taskDefinition.taskDefinitionArn' output.json)" >> $GITHUB_ENV

      - name: Update ECS service with new task definition
        run: |
          aws ecs update-service \
            --cluster tranner-cluster \
            --service ${{ matrix.service }}-service \
            --task-definition ${{ env.TASK_DEF_ARN }}
